# Generated by Django 4.0.2 on 2022-05-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_recipes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
