# Generated by Django 4.0.2 on 2022-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0004_alter_recipes_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
