# Generated by Django 4.0.2 on 2022-05-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0005_alter_recipes_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='content',
            field=models.TextField(blank=True, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название блюда'),
        ),
    ]
